### ISSUE TITLE
Resize Issue

### ISSUE THREAD

**Issue by iseol** [STR-HK/Sticker#1]
Resizing doesn't work.
It is a really big issue.

**Comment by STR-HK** [comment]
🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕

**Comment by hyriph** [comment]
Solved after https://github.com/STR-HK/Sticker/commit/e64354bc648a6816f7b47ae9b71e9366c08fe498 version.
